### ISSUE TITLE
Use Sentinel Terminated Slices

### ISSUE THREAD

**Issue by emekoi** [travisstaloch/art.zig#1]
rather than requiring that the user manually add a `\x00` and performing the check manually, have you considered using [Sentinel Terminated Slices](https://ziglang.org/documentation/master/#Sentinel-Terminated-Slices) instead?

**Comment by travisstaloch** [comment]
i like the idea.  i believe sentinel terminated slices would need to have their lengths increased too.  perhaps this can be done within the library rather than requiring the user to do it.

**Comment by travisstaloch** [comment]
@daurnimator also requested this in discord:
> first, I'll note that you can use [:0]const u8 to require a null terminated slice
