### ISSUE TITLE
node256: num_children should not be kept track of

### ISSUE THREAD

**Issue by lithdew** [travisstaloch/art.zig#11]
This is an issue that I stumbled upon while creating my own port of libart to Zig.

In both [libart](https://github.com/armon/libart/blob/master/src/art.c#L385) and [this repository](https://github.com/travisstaloch/art.zig/blob/master/src/art.zig#L579), the max possible value of `num_children` is 255 (`num_children` is a u8). As an edge case, if you were to fill an entire node with 256 children, `num_children` would attempt to be incremented to 256 in addChild256() which would cause an integer overflow.

libart silently wraps the addition over causing `num_children` to be set to zero (because C), which has been disregarded given that all code having to do with handling nodes with 256 children do not touch the `num_children` field.

However, in Zig, such an increment operation would panic as it is illegal behavior.

The following code below yields an integer overflow panic:

```zig
const std = @import("std");
const art = @import("art.zig");

/// 245.448 milliseconds
pub fn main() !void {
    const gpa = std.heap.c_allocator;

    var tree = art.Art(void).init(gpa);
    defer tree.deinit();

    var keys = try gpa.alloc([32:0]u8, 1_000_000);
    defer gpa.free(keys);

    var rng = std.rand.DefaultPrng.init(0);
    for (keys) |*key| {
        rng.random.bytes(key);
        key[32] = 0;
    }

    var timer = try std.time.Timer.start();

    for (keys) |*key| {
        _ = try tree.insert(key, {});
    }

    std.debug.print("{}\n", .{std.fmt.fmtDuration(timer.read())});
}
```

```
$ zig run benchmarks/art/main.zig -lc --name rheia --main-pkg-path .
thread 1121693 panic: integer overflow
/home/lith/Desktop/rheia/benchmarks/art/art.zig:584:36: 0x22dca9 in benchmarks.art.art.Art(void).addChild256 (rheia)
            n.node256.num_children += 1;
                                   ^
/home/lith/Desktop/rheia/benchmarks/art/art.zig:499:46: 0x210001 in benchmarks.art.art.Art(void).addChild (rheia)
                .node256 => try t.addChild256(n, ref, c, child),
                                             ^
/home/lith/Desktop/rheia/benchmarks/art/art.zig:380:27: 0x20a9bd in benchmarks.art.art.Art(void).recursiveInsertSearch (rheia)
            try t.addChild(n, ref, key[depth], l);
                          ^
/home/lith/Desktop/rheia/benchmarks/art/art.zig:370:47: 0x208399 in benchmarks.art.art.Art(void).recursiveInsert (rheia)
            return try t.recursiveInsertSearch(n, ref, key, value, depth);
                                              ^
/home/lith/Desktop/rheia/benchmarks/art/art.zig:113:49: 0x205545 in benchmarks.art.art.Art(void).insert (rheia)
            const result = try t.recursiveInsert(t.root, &t.root, _key, value, 0);
                                                ^
/home/lith/Desktop/rheia/benchmarks/art/main.zig:23:28: 0x204bce in main (rheia)
        _ = try tree.insert(key, {});
                           ^
```

I'm handling this edge case in my code by not touching the `num_children` field at all when dealing with nodes with 256 children. Here are some snippets from my current implementation which should give a good idea how I handled this edge case:

```zig
pub fn addChild256(self: *N, gpa: *mem.Allocator, ref: *usize, character: u8, child: usize) !void {
    _ = gpa;
    _ = ref;
   self.children[character] = child;
   // Do NOT increment self.metadata.num_children.
}

pub fn copyHeader(self: *Metadata, src: *Metadata) void {
   if (self.node_type != .node_256) {
      self.num_children = src.num_children;
   }
   self.partial_len = src.partial_len;
   mem.copy(u8, &self.partial, src.partial[0..@minimum(max_prefix_len, src.partial_len)]);
}
```

An alternative method for handling this edge case is to bump the type of `num_children` up from a u8 to a u9 so that the max possible number of children is 512. Though, that comes at an expense of introducing padding and increasing the average size of a node which would cause more cache misses on average.

**Comment by travisstaloch** [comment]
Thank you for pointing this out :+1:.  It sounds like it would be best to ignore `num_children` in the node256 code paths or else prevent the overflow.  Seems like this __should__ be handled somehow....  Perhaps using `std.math.add`?  I'll post more after I have a closer look.  

Also thanks for the reproduction.  I'm glad to learn about `std.fmt.fmtDuration` :100:

**Comment by travisstaloch** [comment]
@lithdew this commit addresses the issue.  i'm not convinced it's correct yet, but its better than an overflow crash.  do you have any thoughts about correctness?  i'm just wondering if nodes could be accidentally overwritten once the node256 becomes full?  i've tried to closely follow libart's implementation, so this lib __should__ be making the same choices.  hoping maybe you have an idea as it sounds like you've been working on an art impl as well recently.  

hoping to make some more progress soon but i haven't been able to run my tests yet.  i have discovered build errors in my testing file...

**Comment by lithdew** [comment]
Sorry for the late reply, I reported the issue in amidst still completing certain parts of my libart implementation and noticed that for remove() to function properly, `num_children` needs to be maintained properly for node256.

I think the only compromise that can be made is bumping up num_children from a u8 to a u9 (rather than not touching `num_children`, else remove() will panic).

Also, I've made my code available here - the biggest difference is just that there's some handling for full-prefix paths (non-null-terminated strings) + pointers are tagged and passed around as usize's.

https://github.com/lithdew/rheia/blob/master/benchmarks/mempool/art.zig

**Comment by travisstaloch** [comment]
No worries. Actually your reply was very timely.  I ended up adding back the num_children logic but with a [saturating add](https://github.com/travisstaloch/art.zig/commit/65b30a7a69975b12177bd98ff56ea311ab7fb4fd#diff-4146178bbaae9bc90dd8a27d7d4d398802b8595ad5c18a3de6f27efda8fdde82R576) to prevent overflow.  I think this is a good solution which doesn't add any extra node size or branches.  

Thanks a lot for bringing this to my attention :+1:.  This project has been needing an update for a while (as i'm sure you noticed since you managed to compile it).  A few unused errors with many, many more in the test file.  

The biggest issues was allowing the user to  provide a return type for iter* functions to error.  I hadn't updated since zig tests were changed to return errors :facepalm:.  Also got rid of my previous sentinel/empty node hacks in favor of good ole optionals.  I didn't like the extra checks and preceived noisyness using them brought on.  But now I believe using them is overall simpler.    

Will be checking out your code soon.  Thanks for sharing.

**Comment by travisstaloch** [comment]
Closing this as it seems solved.  Please let me know if anything related comes up in the future or if you see a problem with my sat add solution.

**Comment by lithdew** [comment]
Shouldn't the intrinsic used for saturating add be `extern fn @"llvm.uadd.sat.i8"(u8, u8) u8;`?

**Comment by travisstaloch** [comment]
woops! :sweat_smile: thank you for noticing this.
