### ISSUE TITLE
function to get from Node => key

### ISSUE THREAD

**Issue by travisstaloch** [travisstaloch/art.zig#4]
@daurnimator could you clarify what you meant by:
> I'd like a function to get from Node => key

Also I'm not sure i understand what you were getting at when you said:
> I wonder if nodes could be embedded directly in children

children are *Node(s).  Node is a union of leaf, node4..256 or empty.

**Comment by daurnimator** [comment]
If I have a `*Leaf` (or a pointer to a `Leaf.value`) then I'd like to be able to retrieve the key.

**Comment by travisstaloch** [comment]
Currently insert(), search() and delete() return Result which is a `union(enum) { missing, found: T };` where T is the value type of the Art.  insert and delete return the old value when the key is found. 

Changing `Result.found` to a `Leaf` would make this possible.  But then delete would be returning a destroyed key.  So that's not an option.  

So perhaps changing Result.found to a struct with fields `old: T` and  `leaf: ?*Leaf`.  And delete can leave Result.found.leaf as null.  Does this sound like it would address your use case?

**Comment by travisstaloch** [comment]
@daurnimator did have any thoughts about my last comment?  It might be an overly complex solution, not sure. I did attempt to just create a function from `Leaf.value` to `*Leaf` but ran into some problems which I can't recall right now.

**Comment by travisstaloch** [comment]
@daurnimator I hope these changes address address your comment. I didn't realize when I wrote this that keys should be owned by the client.  Now they are and its possible for a client to free a key after `search()` or `delete()` returns a `.found` result.  Something like this:

```zig
    const result = try tree.delete(line);
    if(result == .found) tree.allocator.free(result.found.key);
```
